# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Age predictor using try/except

try:
  age = int(input('Enter your age:'))
  print(f'Next year: {age + 1}')

except ValueError:
  print('Invalid input!')

