# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

import pandas as pd

print(df['sales'])
print()
print(df[['name','sales']])
print()
print(df.iloc[0])
print()

df.columns = df.columns.str.strip() # removes any extra spaces from the beginning and end of each column name.
df.columns = df.columns.str.lower() # converts every column name to lowercase.
print(df.columns.tolist()) # gives you all the column names of your dataframe & converts that into a normal Python list, so it's easier to read/print.

