# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

import pandas as pd

## First Look Ritual

df.head() # Runs 1st 5 rows by defaults and confirms loading
df.info() # Gives you a summary of the whole dataframe's structure, not the actual data values, but facts about the data.
df.describe() # Gives you summary statistics — but only for the numeric column
print()

df = pd.read_csv('sales.csv')
df

