# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Create a 2D array of 3 students × 3 subjects of scores; print each student's average (arr.mean(axis=1)

scores = np.array([[78, 56, 33], [99, 87, 82], [78, 93, 86]])

print ('Array: ')
print(scores)
print('Shape: ', scores.shape)

avg = scores.mean(axis=1)
for i, a in enumerate(avg):
  print(f'Student-{i+1}: {a:.1f}')