# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""



num_1 = float(input('Enter 1st number: '))
num_2 = float(input('Enter 2nd number: '))
operation = input('Enter operation (+,-,*,/): ')
result = None
if operation == '+':
  result = num_1 + num_2
  print (f'Result: ', result)
  if result > 100:
    print (f'Result is greater than 100')
  else:
    print (f'Result is less than 100')

elif operation == '-':
  result = num_1 - num_2
  print (f'Result: ', result)
  if result > 100:
    print (f'Result is greater than 100')
  else:
    print (f'Result is less than 100')

elif operation == '*':
  result = num_1 * num_2
  print (f'Result: ', result)
  if result > 100:
    print (f'Result is greater than 100')
  else:
    print (f'Result is less than 100')

elif operation == '/':
  if num_2 == 0:
    print (f'Error: Division by zero')
  else:
    result = num_1 / num_2
  print (f'Result: ', result)
  if result > 100:
    print (f'Result is greater than 100')
  else:
    print (f'Result is less than 100')

else:
  print('Invalid operation')

