# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

csv_text = """name,region,sales
Zimal,North,250
Fajar,South
Zumar,East,180
Sukaina,,300
Hira,West,210"""

with open("sales.csv", "w") as f:
  f.write(csv_text)

import pandas as pd

df = pd.read_csv('sales.csv')
df

