# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""



# Build a movie ticket price program under 12 over 65 pays $5, everyone else $10: add student discount using and

age = int (input('Enter your age: '))
discount = input ('Are you a student? (Y/N): ')
price = None

if age <=12 and age >= 65:
  price = 5
  print (f'Ticket Price: $',price)
  if age <=12 and age >= 65 and discount == "Y":
    price = price * 0.5         # Student Discount: 50%
    print (f'5% Student Discount added.You will pay $',price)

elif age >=12 and age <= 65:
  price = 10
  print (f'Ticket Price: $',price)
  if age >=12 and age <= 65 and discount == "Y":
    price = price * 0.5        # Student Discount: 50%
    print (f'5% Student Discount added. You will pay $',price)

else:
  print(f'Invalid Age.')

